plugins:
  - jekyll-remote-theme

whitelist:
  - jekyll-remote-theme

remote_theme: pages-themes/midnight

url: "https://jiminleedev.github.io"
baseurl: "/Study"

title: Jimin Lee's DevLog
tagline: 개발노트
descryption: 공부한 내용을 업로드합니다.
